#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H  -DL_ENDIAN -DTERMIO -O3 -Wall"
  #define PLATFORM "linux-x86_64"
  #define DATE "Tue Jul 18 17:08:41 CST 2017"
#endif
